### ISSUE TITLE
Revisión INSTAGRAM FEED CON BOOTSTRAP

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/rubpercas-Instagram-feed-Bootstrap#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- ¡Bien hecho @rubpercas !
## Estilo de código y limpieza
- ¡Bien hecho!
## Mejores prácticas/comentarios
-  Código bien estructurado y buen uso de Bootstrap para el diseño. 
-  En las línea 62 y 63 tienes unas etiquetas `<a>` abiertas sin cerrar.

**Comment by rubpercas** [comment]
ya está modificado! Muchas gracias!
